version: '3.1'

services:
  pythonapp:
    build: ./
    command: python3 ./hello_world.py
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080